# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=4.0.7@sha256:3aaf1d6948384a1c6f342950a1006ebaef17f6f6a0d470e4534fc95290dc1a83
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
