# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.6@sha256:d41f148e45cb313170e69688755b64d9aa44b84a3d9375f382323f643fac9282
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
