# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=4.0.3@sha256:1c476860da84e05d6e5cb8491934e40c0b2c8325be6d5c3072d7f77b943438ae
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
